<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <DebugSymbols>False</DebugSymbols>
        <DebugType>None</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="GodotSharp">
            <HintPath>I:\SteamLibrary2\SteamApps\common\Atomcraft\data_Atomcraft_windows_x86_64\GodotSharp.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <Target Name="RemoveDepsJson" AfterTargets="Publish">
        <Delete Files="$(PublishDir)$(AssemblyName).deps.json" />
    </Target>

</Project>
