<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <PlatformTarget>x64</PlatformTarget>
        <Prefer32Bit>false</Prefer32Bit>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>0.3.0</Version>

        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <BaseDirectory>GodotMonoModLoader</BaseDirectory>
        <HarmonyVersion>2.4.2</HarmonyVersion>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Atomcraft">
            <HintPath>$(GameInstallDir)\data_Atomcraft_windows_x86_64\Atomcraft.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="GodotSharp">
            <HintPath>$(GameInstallDir)\data_Atomcraft_windows_x86_64\GodotSharp.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Newtonsoft.Json">
            <HintPath>$(GameInstallDir)\data_Atomcraft_windows_x86_64\Newtonsoft.Json.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <PackageReference Include="Godot.SourceGenerators" Version="4.4.0" >
            <OutputItemType>Analyzer</OutputItemType>
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
        </PackageReference>
        <PackageReference Include="Lib.Harmony" Version="$(HarmonyVersion)"  />
    </ItemGroup>

    <PropertyGroup>
        <GeneratedConstants>
namespace GodotMonoModLoader%3B;

internal static class AutogeneratedConstants
{
    public const string VERSION = "$(Version)"%3B;
    public const string HARMONY_VERSION = "$(HarmonyVersion)"%3B;
}
        </GeneratedConstants>
    </PropertyGroup>

    <Target Name="GenerateConstants" BeforeTargets="BeforeCompile">
        <WriteLinesToFile
                File="$(IntermediateOutputPath)AutogeneratedConstants.g.cs"
                Lines="$(GeneratedConstants)"
                Overwrite="true" />
        <ItemGroup>
            <Compile Include="$(IntermediateOutputPath)AutogeneratedConstants.g.cs" />
        </ItemGroup>
    </Target>
    
    <UsingTask
            TaskName="ReplaceText"
            TaskFactory="RoslynCodeTaskFactory"
            AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
        <ParameterGroup>
            <File ParameterType="System.String" Required="true"/>
            <Search ParameterType="System.String" Required="true"/>
            <Replace ParameterType="System.String" Required="true"/>
        </ParameterGroup>
        <Task>
            <Code Type="Fragment" Language="cs">
                <![CDATA[
                  var text = System.IO.File.ReadAllText(File);
                  text = text.Replace(Search, Replace);
                  System.IO.File.WriteAllText(File, text);
                  ]]>
            </Code>
        </Task>
    </UsingTask>
    
    <PropertyGroup>
        <GodotProjectDir>$(MSBuildProjectDirectory)</GodotProjectDir>
        <GodotTargetPlatform>Windows</GodotTargetPlatform>
        <GodotPlatform>Windows</GodotPlatform>
        <GodotTargetArchitecture>x86_64</GodotTargetArchitecture>
        <GodotApiConfiguration>Release</GodotApiConfiguration>
        <GodotRealTIsDouble>false</GodotRealTIsDouble>
        <EnableGodotGenerators>true</EnableGodotGenerators>
    </PropertyGroup>

    <ItemGroup>
        <CompilerVisibleProperty Include="GodotProjectDir" />
        <CompilerVisibleProperty Include="GodotTargetPlatform" />
        <CompilerVisibleProperty Include="GodotPlatform" />
        <CompilerVisibleProperty Include="GodotTargetArchitecture" />
        <CompilerVisibleProperty Include="GodotApiConfiguration" />
        <CompilerVisibleProperty Include="GodotRealTIsDouble" />
        <CompilerVisibleProperty Include="EnableGodotGenerators" />
    </ItemGroup>



    <Target Name="CreateZip" BeforeTargets="AfterBuild">

        <PropertyGroup>
            <Name>GodotMonoModLoader</Name>
            <ReleaseDir>$(MSBuildProjectDirectory)/../Release</ReleaseDir>
            <Dir>$(ReleaseDir)/$(Name)</Dir>
            <SubDir>$(Dir)/$(Name)</SubDir>
            <BootstrapDir>$(SubDir)/Bootstrap</BootstrapDir>
            <Zip>$(Dir).zip</Zip>
            
            <GDScriptsDir>$(ReleaseDir)/../GDScripts</GDScriptsDir>
            <ResourcesDir>$(ProjectDir)Resources</ResourcesDir>
        </PropertyGroup>
        <ItemGroup>
            <GDScripts Include="$(GDScriptsDir)\**\*" />
            <Resources Include="$(ResourcesDir)\**\*" />
        </ItemGroup>
        
        
        <RemoveDir Directories="$(Dir)" />

        <MakeDir Directories="$(SubDir)" />
        
        <MSBuild Projects="..\GodotMonoModLoaderBootstrap\GodotMonoModLoaderBootstrap.csproj" BuildInParallel="$(BuildInParallel)" Targets="Clean;Publish"
                 Properties="Configuration=$(Configuration);
                 RuntimeIdentifier=win-x64;
                 PublishDir=$(BootstrapDir)"
        />
        
        <Copy SourceFiles="..\GodotMonoModLoaderBootstrap\GodotMonoModLoaderBootstrap.runtimeconfig.json"
              DestinationFolder="$(BootstrapDir)" />
        
<!--        Build the c# version of the Proxy. Not used in favor of the c++ version.-->
<!--        <MSBuild Projects="..\GodotMonoModLoaderProxy\GodotMonoModLoaderProxy.csproj" BuildInParallel="$(BuildInParallel)" Targets="Clean;Publish"-->
<!--                 Properties="Configuration=$(Configuration);-->
<!--                 RuntimeIdentifier=win-x64;-->
<!--                 PublishDir=$(Dir)"-->
<!--        />-->
        
        <MSBuild Projects="..\GodotMonoModLoaderProxy\GodotMonoModLoaderProxy.Native.vcxproj" BuildInParallel="$(BuildInParallel)" Targets="Clean;Build"
                 Properties="Configuration=$(Configuration);
                 Platform=x64;
                 OutDir=$(Dir);"
        />
        
        <MSBuild Projects="..\ModLoaderPatch\ModLoaderPatch.csproj" BuildInParallel="$(BuildInParallel)" Targets="Clean;Build">
            <Output TaskParameter="TargetOutputs" ItemName="ModLoaderPatchOutput" />
        </MSBuild>
        
        <MSBuild Projects="..\AtomcraftPatcher\AtomcraftPatcher.csproj" BuildInParallel="$(BuildInParallel)" Targets="Clean;Publish"
                 Properties="Configuration=$(Configuration);
                  RuntimeIdentifier=win-x64;
                  PublishDir=$(Dir)"/>
        
        <MSBuild Projects="..\AtomcraftPatcher\AtomcraftPatcher.csproj" BuildInParallel="$(BuildInParallel)" Targets="Clean;Publish"
                 Properties="Configuration=$(Configuration);
                  RuntimeIdentifier=linux-x64;
                  PublishDir=$(Dir)"/>
        

        <Copy   SourceFiles="$(ReleaseDir)/../$(Name).gd"
                DestinationFolder="$(Dir)"/>

        <ReplaceText
                File="$(Dir)/$(Name).gd"
                Search="@VERSION@"
                Replace="$(Version)" />
        <ReplaceText
                File="$(Dir)/$(Name).gd"
                Search="@HARMONY_VERSION@"
                Replace="$(HarmonyVersion)" />

        <Copy   SourceFiles="@(ModLoaderPatchOutput)"
                DestinationFolder="$(SubDir)" />

        <Copy   SourceFiles="$(TargetPath)"
                DestinationFolder="$(SubDir)" />

        <Copy   SourceFiles="$(TargetDir)0Harmony.dll"
                DestinationFolder="$(SubDir)" />

        <Copy   Condition="Exists($(GDScriptsDir))"
                SourceFiles="@(GDScripts)"
                DestinationFiles="@(GDScripts->'$(SubDir)/%(RecursiveDir)%(Filename)%(Extension)')"/>
        
        <Copy   Condition="Exists($(ResourcesDir))"
                SourceFiles="@(Resources)"
                DestinationFiles="@(Resources->'$(SubDir)/Resources/%(RecursiveDir)%(Filename)%(Extension)')"/>
        
        <Copy   SourceFiles="$(MSBuildProjectDirectory)/../README.md"
                DestinationFiles="$(Dir)/ModLoaderInstructions.md"/>

        <Delete Files="$(Zip)" />

        <ZipDirectory
                SourceDirectory="$(Dir)"
                DestinationFile="$(Zip)"
                Overwrite="true" />

        <RemoveDir Directories="$(Dir)" />

        <Message
                Importance="high"
                Text="&#xA;GodotMonoModLoader ZIP created: $(Zip)" />

    </Target>
    
</Project>
